"""Interview endpoints."""

import asyncio
from datetime import UTC, datetime, timedelta
from uuid import UUID

from fastapi import APIRouter, status

from job_agent_os.api.deps import CurrentUser, DBSession
from job_agent_os.api.response import success_response
from job_agent_os.core.error_codes import ErrorCode
from job_agent_os.core.exceptions import NotFoundException
from job_agent_os.core.utils import generate_uuid_obj, utc_now
from job_agent_os.schemas.interview import QuestionGenerateRequest

router = APIRouter()

# In-memory task store for async question generation
_generation_tasks: dict[str, dict] = {}

# TTL for completed tasks (30 minutes)
_TASK_TTL_MINUTES = 30


def _cleanup_expired_tasks() -> None:
    """Remove completed tasks older than _TASK_TTL_MINUTES."""
    now = datetime.now(UTC)
    expired_keys = []
    for task_id, task in _generation_tasks.items():
        if task.get("status") in ("completed", "failed"):
            created_at_str = task.get("created_at")
            if created_at_str:
                try:
                    created_at = datetime.fromisoformat(created_at_str)
                    if created_at.tzinfo is None:
                        created_at = created_at.replace(tzinfo=UTC)
                    if now - created_at > timedelta(minutes=_TASK_TTL_MINUTES):
                        expired_keys.append(task_id)
                except (ValueError, TypeError):
                    expired_keys.append(task_id)
    for key in expired_keys:
        _generation_tasks.pop(key, None)


@router.post("/questions", status_code=status.HTTP_202_ACCEPTED)
async def generate_questions(
    request: QuestionGenerateRequest,
    db: DBSession,
    user: CurrentUser,
) -> dict:
    """Trigger async interview question generation."""
    task_id = str(generate_uuid_obj())

    _generation_tasks[task_id] = {
        "task_id": task_id,
        "status": "processing",
        "job_id": str(request.job_id),
        "resume_id": str(request.resume_id) if request.resume_id else None,
        "question_types": request.question_types,
        "difficulty": request.difficulty,
        "count": request.count,
        "created_at": utc_now().isoformat(),
        "result": None,
    }

    # Start background generation
    asyncio.create_task(_generate_questions_background(task_id, request))

    return success_response(
        data={"task_id": task_id, "status": "processing"},
        message="Question generation started",
    )


@router.get("/questions/{task_id}")
async def get_generation_result(
    task_id: str,
    db: DBSession,
    user: CurrentUser,
) -> dict:
    """Get question generation result."""
    # Clean up expired tasks before accessing
    _cleanup_expired_tasks()
    task = _generation_tasks.get(task_id)
    if not task:
        raise NotFoundException(
            message="Task not found",
            code=ErrorCode.RESOURCE_NOT_FOUND,
        )

    return success_response(
        data={
            "task_id": task["task_id"],
            "status": task["status"],
            "result": task["result"],
        }
    )


async def _generate_questions_background(
    task_id: str, request: QuestionGenerateRequest
) -> None:
    """Background task to generate interview questions.

    In full implementation (Phase 3), this would call the Interview Agent
    with real LLM generation. For now, returns placeholder structure.
    """
    # Simulate processing time
    await asyncio.sleep(0.1)

    questions = []
    q_id = 1

    if "technical" in request.question_types:
        for i in range(min(request.count // 2 + 1, request.count)):
            questions.append(
                {
                    "id": q_id,
                    "type": "technical",
                    "category": "general",
                    "difficulty": request.difficulty if request.difficulty != "mixed" else "medium",
                    "question": f"[Placeholder] Technical question {q_id} for job {request.job_id}",
                    "reference_answer": "Reference answer will be generated by Interview Agent in Phase 3.",
                    "scoring_criteria": ["Correctness", "Depth", "Clarity"],
                    "follow_up": None,
                }
            )
            q_id += 1

    if "behavioral" in request.question_types:
        remaining = request.count - len(questions)
        for i in range(max(remaining, 1)):
            questions.append(
                {
                    "id": q_id,
                    "type": "behavioral",
                    "category": "STAR",
                    "difficulty": "medium",
                    "question": f"[Placeholder] Behavioral question {q_id} (STAR format)",
                    "reference_answer": "Reference answer will be generated by Interview Agent in Phase 3.",
                    "scoring_criteria": ["Situation clarity", "Action specificity", "Result impact"],
                    "follow_up": None,
                }
            )
            q_id += 1

    _generation_tasks[task_id]["status"] = "completed"
    _generation_tasks[task_id]["result"] = {
        "status": "completed",
        "job_title": None,
        "questions": questions[: request.count],
    }

